Controllers/UtilitiesController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Syncfusion.EJ2.Base;
using API_System.BLL;
using API_System.Models;

namespace API_System.Controllers
{
    public class UtilitiesController : Controller
    {
        private IWebHostEnvironment hostingEnv;
        private API_SystemContext context;
        private IUserService userInfor;

        public UtilitiesController(API_SystemContext Context, IWebHostEnvironment env, IUserService _userinfo)

        {
            this.hostingEnv = env;
            this.context = Context;
            this.userInfor = _userinfo;
        }

        public IActionResult Index()
        {
            return View();
        }

        #region Roles

        public IActionResult Roles()
        {           

            return View();
        }
        public ActionResult RolesDataSource([FromBody] DataManagerRequest dm)
        {

            var _data = context.AspNetRoles.AsNoTracking().OrderByDescending(o => o.Id).ToList();
            IEnumerable data = _data;
            int count = _data.Count();

            DataOperations operation = new DataOperations();
            //Performing filtering operation
            if (dm.Where != null)
            {
                data = operation.PerformFiltering(data, dm.Where, "and");
                var filtered = (IEnumerable<object>)data;
                count = filtered.Count();
            }
            //Performing search operation
            if (dm.Search != null)
            {
                data = operation.PerformSearching(data, dm.Search);
                var searched = (IEnumerable<object>)data;
                count = searched.Count();
            }
            //Performing sorting operation
            if (dm.Sorted != null)
                data = operation.PerformSorting(data, dm.Sorted);

            //Performing paging operations
            if (dm.Skip > 0)
                data = operation.PerformSkip(data, dm.Skip);
            if (dm.Take > 0)
                data = operation.PerformTake(data, dm.Take);

            return Json(new { result = data, count = count }, new Newtonsoft.Json.JsonSerializerSettings());
        }

        public IActionResult AddRolePartial([FromBody] CRUDModel<AspNetRoles> value)
        {
           
            return PartialView("_DialogRoleAddPartial", value.Value);
        }
        public ActionResult EditRolePartial([FromBody] CRUDModel<AspNetRoles> value)
        {          

            return PartialView(value.Value);
        }

        public string CheckRoleId()
        {
            //string code = "0";
            string code = "awusgfgdf-ewqas-jkgr-zure-bncvxmkhipqw";
            int result = 0;
            result = context.AspNetRoles.ToList().Count();
            code += (result + 1);
            var x = new AspNetRoles()
            {
                Id = code
            };

            return (code);
        }

        public ActionResult DialogInsertRole([FromBody] CRUDModel<AspNetRoles> value)
        {
            string result = string.Empty;

            AspNetRoles _table = context.AspNetRoles.FirstOrDefault(o =>
            (o.Id == value.Value.Id));


            if (_table == null)
            {
                //Save into ASPNet Roles table
                AspNetRoles table = new AspNetRoles();

                table.Id = CheckRoleId();
                table.Name = value.Value.Name;
                table.NormalizedName = value.Value.Name.ToUpper();

                //table.DateAdded = DateTime.Now;
                //table.AddedBy = userInfor.GetUser().Identity.Name;

                context.AspNetRoles.Add(table);
                context.SaveChanges();

            }
            else
            {
                this.DialogUpdateRoles(value);
            }
            return Json(value.Value);
        }

        public ActionResult DialogUpdateRoles([FromBody] CRUDModel<AspNetRoles> value)
        {
            AspNetRoles table = context.AspNetRoles.FirstOrDefault(o =>
             (o.Id == value.Value.Id));

            if (table != null)
            {
                table.Name = value.Value.Name;
                
                //table.DateEdited = DateTime.Now;
                //table.EditedBy = userInfor.GetUser().Identity.Name;

                context.Entry(table).CurrentValues.SetValues(value);
                context.Entry(table).State = EntityState.Modified;

                context.SaveChanges();

                try
                {

                    TempData["Success"] = "Record Saved Successfully!";
                }



                catch (DbEntityValidationException dbEx)
                {
                    foreach (var validationErrors in dbEx.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            TempData["Success"] += string.Format("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                            System.Console.WriteLine("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                        }
                    }
                }
            }
            else
            {
                this.DialogInsertRole(value);
            }

            return Json(value.Value);
        }

        #endregion Roles

        #region Departments

        public IActionResult Departments()
        {
            return View();
        }
        public ActionResult DepartmentsDataSource([FromBody] DataManagerRequest dm)
        {

            var _data = context.ADepartment.AsNoTracking().OrderByDescending(o => o.DepartmentId).ToList();
            IEnumerable data = _data;
            int count = _data.Count();

            DataOperations operation = new DataOperations();
            //Performing filtering operation
            if (dm.Where != null)
            {
                data = operation.PerformFiltering(data, dm.Where, "and");
                var filtered = (IEnumerable<object>)data;
                count = filtered.Count();
            }
            //Performing search operation
            if (dm.Search != null)
            {
                data = operation.PerformSearching(data, dm.Search);
                var searched = (IEnumerable<object>)data;
                count = searched.Count();
            }
            //Performing sorting operation
            if (dm.Sorted != null)
                data = operation.PerformSorting(data, dm.Sorted);

            //Performing paging operations
            if (dm.Skip > 0)
                data = operation.PerformSkip(data, dm.Skip);
            if (dm.Take > 0)
                data = operation.PerformTake(data, dm.Take);

            return Json(new { result = data, count = count }, new Newtonsoft.Json.JsonSerializerSettings());
        }

        public IActionResult AddDepartmentPartial([FromBody] CRUDModel<ADepartment> value)
        {

            return PartialView("_DialogDepartmentAddPartial", value.Value);
        }
        public ActionResult EditDepartmentPartial([FromBody] CRUDModel<ADepartment> value)
        {

            return PartialView(value.Value);
        }

        public int CheckDepartmentCode()
        {
            var depcode = context.ADepartment.OrderByDescending(o => o.DepartmentId).Take(1).Select(f => f.DepartmentId).FirstOrDefault();
            return (depcode);
        }

        public ActionResult DialogInsertDepartment([FromBody] CRUDModel<ADepartment> value)
        {
            string result = string.Empty;

            ADepartment _table = context.ADepartment.FirstOrDefault(o =>
            (o.DepartmentId == value.Value.DepartmentId));


            if (_table == null)
            {                
                ADepartment table = new ADepartment();

                if (string.IsNullOrEmpty(table.DepartmentId.ToString()) || table.DepartmentId == 0)
                {
                    var newCode = CheckDepartmentCode();
                    table.DepartmentId = ++newCode;
                }

                table.Department = value.Value.Department;

                //table.DateAdded = DateTime.Now;
                //table.AddedBy = userInfor.GetUser().Identity.Name;

                context.ADepartment.Add(table);
                context.SaveChanges();

            }
            else
            {
                this.DialogUpdateDepartment(value);
            }
            return Json(value.Value);
        }

        public ActionResult DialogUpdateDepartment([FromBody] CRUDModel<ADepartment> value)
        {
            ADepartment table = context.ADepartment.FirstOrDefault(o =>
             (o.DepartmentId == value.Value.DepartmentId));

            if (table != null)
            {
                table.Department = value.Value.Department;

                //table.DateEdited = DateTime.Now;
                //table.EditedBy = userInfor.GetUser().Identity.Name;

                context.Entry(table).CurrentValues.SetValues(value);
                context.Entry(table).State = EntityState.Modified;

                context.SaveChanges();

                try
                {

                    TempData["Success"] = "Record Saved Successfully!";
                }



                catch (DbEntityValidationException dbEx)
                {
                    foreach (var validationErrors in dbEx.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {

Views/Utilities/Departments.cshtml
@{
    ViewData["Title"] = "Departments";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb" style="margin-top:5px;">

    <li class="breadcrumb-item active" style="width:100%; background-color: black; color:white; font-family:Cambria; padding:5px; font:bolder">Add/Edit - Departments</li>
</ol>
@*<partial name="MessagePartial" />*@
<ejs-grid id="MainGrid"
          allowPaging="true" allowResizing="true" allowTextWrap="true" gridLines="Both"
          allowSorting="true" allowReordering="true" allowGrouping="true" showColumnChooser="true"
          toolbar="@(new List<string>() { "Search", "Add", "Edit", "Delete","Update","Cancel" , "ExcelExport" , "CsvExport" ,"PdfExport","ColumnChooser"})"
          allowFiltering="true" allowSelection="true" allowExcelExport="true"
          allowPdfExport="true" toolbarClick="toolbarClick" actionComplete="onEdit" actionBegin="OnBegin">
    <e-grid-searchSettings fields="@(new string[] {"DepartmentId","Department"})" operator="contains" ignoreCase="true"></e-grid-searchSettings>

    <e-data-manager url="/Utilities/DepartmentsDataSource" insertUrl="/Utilities/DialogInsertDepartment" updateUrl="/Utilities/DialogUpdateDepartment" adaptor="UrlAdaptor"></e-data-manager>

    <e-grid-pagesettings pageSize="7" pageSizes="true" pageCount="4" />
    <e-grid-filterSettings type="Excel"></e-grid-filterSettings>
    <e-grid-editSettings allowAdding="true" allowDeleting="true" allowEditing="true" mode="Dialog" template='#dialogtemplate'></e-grid-editSettings>
    <e-grid-selectionsettings type="Single"></e-grid-selectionsettings>
    <e-grid-columns>
        <e-grid-column type="checkbox" width="50"></e-grid-column>
        <e-grid-column field="DepartmentId" width="280" headerText="Department Code" visible="false" isPrimaryKey="true" isIdentity="true"></e-grid-column>
        <e-grid-column field="Department" headerText="Department" allowEditing="false" visible="true"></e-grid-column>

    </e-grid-columns>
</ejs-grid>



<script>
    function toolbarClick(args) {
        if (args.item.id === this.element.id + '_pdfexport') {
            this.pdfExport();
        }
        if (args.item.id === this.element.id + '_csvexport') {
            this.csvExport();
        }
        if (args.item.id === this.element.id + '_excelexport') {
            this.excelExport();
        }
    }


    function onEdit(args) {
        if (args.requestType === 'beginEdit' || args.requestType === 'add') {
            let spinner = ej.popups.createSpinner({ target: args.dialog.element });
            //ej.popups.showSpinner(args.dialog.element);

            //#####
           var data = args.rowData;

            window.args = args.requestType;

            // For custom save button
            args.dialog.btnObj[0].destroy();
            args.dialog.btnObj[0].element.id = "save";

            var progressSaveButton = new ejs.splitbuttons.ProgressButton({
                content: 'Save',
                enableProgress: true,
                animationSettings: { effect: 'SlideRight' },
                spinSettings: { position: 'Center' },
                cssClass: 'e-success',
            }); progressSaveButton.appendTo('#save');

            // For custom cancel button
            args.dialog.btnObj[1].destroy();
            args.dialog.btnObj[1].element.id = "cancel";

            var progressCancelButton = new ejs.splitbuttons.ProgressButton({
                content: 'Cancel',
                enableProgress: true,
                animationSettings: { effect: 'SlideRight' },
                spinSettings: { position: 'Center' },
                cssClass: 'e-danger',

            });
            progressCancelButton.appendTo('#cancel');

            // saving the edit action
            document.getElementById('save').addEventListener('click', function (args) {
                //onclick = savess();
            }.bind(this));

            // Cancelling the edit action
            document.getElementById('cancel').addEventListener('click', function (args) {
                //onclick = cancelss();

            }.bind(this));

             //#####


            if (args.requestType === 'beginEdit') {

                args.dialog.header = args.requestType === 'beginEdit' ? 'Edit Department: ' + args.rowData['Department'] : 'Department';

                    var ajax = new ej.base.Ajax({
                        url: "@Url.Action("EditDepartmentPartial", "Utilities")", //render the partial view
                        type: "POST",
                        data: JSON.stringify({ value: args.rowData})
                    });
                    ajax.send().then(function (data) {
                        appendElement(data, args.form); //Render the edit form with selected record
                        args.form.elements.namedItem('DepartmentId').focus();
                        ej.popups.hideSpinner(args.dialog.element);

                    }).catch(function (xhr) {
                        console.log(xhr);
                        ej.popups.hideSpinner(args.dialog.element);
                    });
                }

            if (args.requestType === 'add') {

                args.dialog.header = 'Add a Department'


                  var ajax = new ej.base.Ajax({
                        url: "@Url.Action("AddDepartmentPartial", "Utilities")", //render the partial view
                        type: "POST",
                        contentType: "application/json",
                        data: JSON.stringify({ value: args.rowData})
                    });
                    ajax.send().then(function (data) {
                        appendElement(data, args.form); //Render the edit form with selected record
                        args.form.elements.namedItem('DepartmentId').focus();
                        ej.popups.hideSpinner(args.dialog.element);

                    }).catch(function (xhr) {
                        console.log(xhr);
                        ej.popups.hideSpinner(args.dialog.element);
                    });
                }
        }
        else if(args.requestType=="save") {
             var grid = document.getElementById("MainGrid").ej2_instances[0];
              grid.refresh(); // refresh the Grid.
         }
    }

    function appendElement(elementString, form) {
            form.querySelector("#dialogTemp").innerHTML = elementString;
            var script = document.createElement('script');
            script.type = "text/javascript";
            var serverScript = form.querySelector("#dialogTemp").querySelector('script');
            script.textContent = serverScript.innerHTML;
            document.head.appendChild(script);
            serverScript.remove();
    }

      function OnBegin(args) {
          if (args.requestType == 'save') {

              var DepartmentName = document.getElementById("Department").ej2_instances[0];
              var _DepartmentName = DepartmentName.value;

              if ((_DepartmentName == null || _DepartmentName == "0" || _DepartmentName == "" || _DepartmentName == " ")) {

                 alert("Please enter a Department")
                 args.cancel = true;
              }

        }
    }

</script>


<script id='dialogtemplate' type="text/x-template">
    <div id="dialogTemp">
    </div>
</script>
<style type="text/css">
</style>

@*Change size of the add and edit dialog*@

<style>
    #MainGrid_dialogEdit_wrapper {
        min-height: 400px;
        min-width: 50%;
    }
</style>

Views/Utilities/EditDepartmentPartial.cshtml
@model API_System.Models.ADepartment
@using Syncfusion.EJ2

<div id="defaultTab" style="width: 100%; padding-left:3%; padding-right:3%">

    <div class="panel-group" id="accordion">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h5 style="width:100%; background-color: cadetblue; color:white; font-family:Cambria; padding:5px;" class="panel-title ">
                    <a data-toggle="collapse" class="dialogClass" data-parent="#accordion" href="#collapse2">
                        Departments Module
                    </a>
                </h5>
            </div>

            <br /><br />

            <div class="panel-body">
                <div class="row material2">

                    <div class="col-xs-6 col-sm-6 col-lg-6 col-md-6" hidden>
                        <ejs-textbox id="DepartmentId" asp-for="DepartmentId" cssClass="e-outline" placeholder="Department Id" floatLabelType="Auto" name="DepartmentId" type='text' disabled value="@Model.DepartmentId"></ejs-textbox>
                    </div>

                    <div class="col-xs-6 col-sm-6 col-lg-6 col-md-6">
                        <ejs-textbox id="Department" asp-for="Department" cssClass="e-outline" placeholder="Department" floatLabelType="Auto" name="Department" type='text' value="@Model.Department"></ejs-textbox>
                    </div>
                </div>

            </div>

        </div>
    </div>
</div>

<ejs-scripts></ejs-scripts>
<script>
    function onFileRemove(args) {
        args.postRawFile = false;
    }
    //var dropElement = document.getElementsByClassName('control-fluid')[0];
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<style>
    .dialogClass {
        color: white;
    }
</style>
<style>
    .panel-default > .panel-heading {
        background-color: #56ad61;
        color: white;
    }
</style>

Views/Utilities/EditOrganizationPartial.cshtml
@model API_System.Models.AOrganization
@using Syncfusion.EJ2


<div id="defaultTab" style="width: 100%; padding-left:3%; padding-right:3%">

    <div class="panel-group" id="accordion">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h5 style="width:100%; background-color: cadetblue; color:white; font-family:Cambria; padding:5px;" class="panel-title ">
                    <a data-toggle="collapse" class="dialogClass" data-parent="#accordion" href="#collapse2">
                        Organizations Module
                    </a>
                </h5>
            </div>

            <br /><br />

            <div class="panel-body">
                <div class="row material2">

                    <div class="col-xs-6 col-sm-6 col-lg-6 col-md-6" hidden>
                        <ejs-textbox id="OrganizationId" asp-for="OrganizationId" cssClass="e-outline" placeholder="Organization Id" floatLabelType="Auto" name="DepartmentId" type='text' disabled value="@Model.OrganizationId"></ejs-textbox>
                    </div>

                    <div class="col-xs-6 col-sm-6 col-lg-6 col-md-6">
                        <ejs-textbox id="Organization" asp-for="Organization" cssClass="e-outline" placeholder="Organization" floatLabelType="Auto" name="Organization" type='text' value="@Model.Organization"></ejs-textbox>
                    </div>
                </div>

            </div>

        </div>
    </div>
</div>

<ejs-scripts></ejs-scripts>
<script>
    function onFileRemove(args) {
        args.postRawFile = false;
    }
    //var dropElement = document.getElementsByClassName('control-fluid')[0];
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<style>
    .dialogClass {
        color: white;
    }
</style>
<style>
    .panel-default > .panel-heading {
        background-color: #56ad61;
        color: white;
    }
</style>

Views/Utilities/EditRolePartial.cshtml
@model API_System.Models.AspNetRoles
@using Syncfusion.EJ2

<div id="defaultTab" style="width: 100%; padding-left:3%; padding-right:3%">

    <div class="panel-group" id="accordion">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h5 style="width:100%; background-color: cadetblue; color:white; font-family:Cambria; padding:5px;" class="panel-title ">
                    <a data-toggle="collapse" class="dialogClass" data-parent="#accordion" href="#collapse2">
                        Roles Module
                    </a>
                </h5>
            </div>

            <br /><br />

            <div class="panel-body">
                <div class="row material2">

                    <div class="col-xs-6 col-sm-6 col-lg-6 col-md-6" hidden>
                        <ejs-textbox id="Id" asp-for="Id" cssClass="e-outline" placeholder="Role Id" floatLabelType="Auto" name="Id" type='text' disabled value="@Model.Id"></ejs-textbox>
                    </div>

                    <div class="col-xs-6 col-sm-6 col-lg-6 col-md-6">
                        <ejs-textbox id="Name" asp-for="Name" cssClass="e-outline" placeholder="Role" floatLabelType="Auto" name="Name" type='text' value="@Model.Name"></ejs-textbox>
                    </div>
                </div>

            </div>

        </div>
    </div>
</div>

<ejs-scripts></ejs-scripts>
<script>
    function onFileRemove(args) {
        args.postRawFile = false;
    }
    //var dropElement = document.getElementsByClassName('control-fluid')[0];
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<style>
    .dialogClass {
        color: white;
    }
</style>
<style>
    .panel-default > .panel-heading {
        background-color: #56ad61;
        color: white;
    }
</style>

Views/Utilities/Organization.cshtml
@{
    ViewData["Title"] = "Organization";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb" style="margin-top:5px;">

    <li class="breadcrumb-item active" style="width:100%; background-color: black; color:white; font-family:Cambria; padding:5px; font:bolder">Add/Edit - Organization</li>
</ol>
@*<partial name="MessagePartial" />*@
<ejs-grid id="MainGrid"
          allowPaging="true" allowResizing="true" allowTextWrap="true" gridLines="Both"
          allowSorting="true" allowReordering="true" allowGrouping="true" showColumnChooser="true"
          toolbar="@(new List<string>() { "Search", "Add", "Edit", "Delete","Update","Cancel" , "ExcelExport" , "CsvExport" ,"PdfExport","ColumnChooser"})"
          allowFiltering="true" allowSelection="true" allowExcelExport="true"
          allowPdfExport="true" toolbarClick="toolbarClick" actionComplete="onEdit" actionBegin="OnBegin">
    <e-grid-searchSettings fields="@(new string[] {"OrganizationId","Organization"})" operator="contains" ignoreCase="true"></e-grid-searchSettings>

    <e-data-manager url="/Utilities/OrganizationDataSource" insertUrl="/Utilities/DialogInsertOrganization" updateUrl="/Utilities/DialogUpdateOrganization" adaptor="UrlAdaptor"></e-data-manager>

    <e-grid-pagesettings pageSize="7" pageSizes="true" pageCount="4" />
    <e-grid-filterSettings type="Excel"></e-grid-filterSettings>
    <e-grid-editSettings allowAdding="true" allowDeleting="true" allowEditing="true" mode="Dialog" template='#dialogtemplate'></e-grid-editSettings>
    <e-grid-selectionsettings type="Single"></e-grid-selectionsettings>
    <e-grid-columns>
        <e-grid-column type="checkbox" width="50"></e-grid-column>
        <e-grid-column field="OrganizationId" width="280" headerText="Organization Code" visible="false" isPrimaryKey="true" isIdentity="true"></e-grid-column>
        <e-grid-column field="Organization" headerText="Organization" allowEditing="false" visible="true"></e-grid-column>

    </e-grid-columns>
</ejs-grid>



<script>
    function toolbarClick(args) {
        if (args.item.id === this.element.id + '_pdfexport') {
            this.pdfExport();
        }
        if (args.item.id === this.element.id + '_csvexport') {
            this.csvExport();
        }
        if (args.item.id === this.element.id + '_excelexport') {
            this.excelExport();
        }
    }


    function onEdit(args) {
        if (args.requestType === 'beginEdit' || args.requestType === 'add') {
            let spinner = ej.popups.createSpinner({ target: args.dialog.element });
            //ej.popups.showSpinner(args.dialog.element);

            //#####
           var data = args.rowData;

            window.args = args.requestType;

            // For custom save button
            args.dialog.btnObj[0].destroy();
            args.dialog.btnObj[0].element.id = "save";

            var progressSaveButton = new ejs.splitbuttons.ProgressButton({
                content: 'Save',
                enableProgress: true,
                animationSettings: { effect: 'SlideRight' },
                spinSettings: { position: 'Center' },
                cssClass: 'e-success',
            }); progressSaveButton.appendTo('#save');

            // For custom cancel button
            args.dialog.btnObj[1].destroy();
            args.dialog.btnObj[1].element.id = "cancel";

            var progressCancelButton = new ejs.splitbuttons.ProgressButton({
                content: 'Cancel',
                enableProgress: true,
                animationSettings: { effect: 'SlideRight' },
                spinSettings: { position: 'Center' },
                cssClass: 'e-danger',

            });
            progressCancelButton.appendTo('#cancel');

            // saving the edit action
            document.getElementById('save').addEventListener('click', function (args) {
                //onclick = savess();
            }.bind(this));

            // Cancelling the edit action
            document.getElementById('cancel').addEventListener('click', function (args) {
                //onclick = cancelss();

            }.bind(this));

             //#####


            if (args.requestType === 'beginEdit') {

                args.dialog.header = args.requestType === 'beginEdit' ? 'Edit Organization: ' + args.rowData['Organization'] : 'Organization';

                    var ajax = new ej.base.Ajax({
                        url: "@Url.Action("EditOrganizationPartial", "Utilities")", //render the partial view
                        type: "POST",
                        data: JSON.stringify({ value: args.rowData})
                    });
                    ajax.send().then(function (data) {
                        appendElement(data, args.form); //Render the edit form with selected record
                        args.form.elements.namedItem('OrganizationId').focus();
                        ej.popups.hideSpinner(args.dialog.element);

                    }).catch(function (xhr) {
                        console.log(xhr);
                        ej.popups.hideSpinner(args.dialog.element);
                    });
                }

            if (args.requestType === 'add') {

                args.dialog.header = 'Add an organization'


                  var ajax = new ej.base.Ajax({
                        url: "@Url.Action("AddOrganizationPartial", "Utilities")", //render the partial view
                        type: "POST",
                        contentType: "application/json",
                        data: JSON.stringify({ value: args.rowData})
                    });
                    ajax.send().then(function (data) {
                        appendElement(data, args.form); //Render the edit form with selected record
                        args.form.elements.namedItem('OrganizationId').focus();
                        ej.popups.hideSpinner(args.dialog.element);

                    }).catch(function (xhr) {
                        console.log(xhr);
                        ej.popups.hideSpinner(args.dialog.element);
                    });
                }
        }
        else if(args.requestType=="save") {
             var grid = document.getElementById("MainGrid").ej2_instances[0];
              grid.refresh(); // refresh the Grid.
         }
    }

    function appendElement(elementString, form) {
            form.querySelector("#dialogTemp").innerHTML = elementString;
            var script = document.createElement('script');
            script.type = "text/javascript";
            var serverScript = form.querySelector("#dialogTemp").querySelector('script');
            script.textContent = serverScript.innerHTML;
            document.head.appendChild(script);
            serverScript.remove();
    }

      function OnBegin(args) {
          if (args.requestType == 'save') {

              var OrganizationName = document.getElementById("Organization").ej2_instances[0];
              var _OrganizationName = OrganizationName.value;

              if ((_OrganizationName == null || _OrganizationName == "0" || _OrganizationName == "" || _OrganizationName == " ")) {

                 alert("Please enter an Organization")
                 args.cancel = true;
              }
        }
    }

</script>


<script id='dialogtemplate' type="text/x-template">
    <div id="dialogTemp">
    </div>
</script>
<style type="text/css">
</style>

@*Change size of the add and edit dialog*@

<style>
    #MainGrid_dialogEdit_wrapper {
        min-height: 400px;
        min-width: 50%;
    }
</style>